apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlops-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mlops
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
